[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
ksp = "2.3.2"
coroutines = "1.10.2"
lifecycle-vm-nav3 = "2.10.0"
serializationJson = "1.9.0"
paging = "3.3.6"
paging-ui = "3.4.0-beta01"
nav3 = "1.0.0"
hilt = "2.57.2"
hiltNavigation = "1.3.0"
retrofit = "3.0.0"
okHttp = "5.3.2"
junit = "6.0.2"
kotest = "6.0.7"
mockk = "1.14.7"
turbine = "1.2.1"

[libraries]

#Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
lifecycle-vm-nav3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle-vm-nav3" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

# Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# Hilt/Dagger
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compose-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

# Network
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-compose-paging-ui = { module = "androidx.paging:paging-compose", version.ref = "paging" }
nav3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3" }
nav3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3" }

# Testing
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
kotest = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "lifecycle-vm-nav3",
    "androidx-activity-compose",
    "coroutines-android",
    "coroutines-core",
    "kotlinx-serialization-json"
]
di = ["dagger-hilt", "hilt-compose-navigation"]
network = ["okhttp", "okhttp-logging", "retrofit", "retrofit-converter"]
ui = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    'androidx-compose-paging',
    "androidx-compose-paging-ui",
    "nav3-runtime",
    "nav3-ui",
]
testing = ["junit", "kotest", "mockk", "coroutines-test", "hilt-test", "turbine"]
debugging = ["androidx-compose-ui-tooling"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

